# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import m2n_bootstrap_pb2 as m2n__bootstrap__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in m2n_bootstrap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class M2nBootstrapServiceStub(object):
    """Ephemeral control-plane broker for a coordinator-defined NCCL communicator.
    NeMo RL/Dynamo owns membership and rank assignment; ModelExpress only stores
    an immutable UID record and fences aborted or expired attempts.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishBootstrap = channel.unary_unary(
                '/model_express.m2n_bootstrap.M2nBootstrapService/PublishBootstrap',
                request_serializer=m2n__bootstrap__pb2.PublishM2nBootstrapRequest.SerializeToString,
                response_deserializer=m2n__bootstrap__pb2.PublishM2nBootstrapResponse.FromString,
                _registered_method=True)
        self.GetBootstrap = channel.unary_unary(
                '/model_express.m2n_bootstrap.M2nBootstrapService/GetBootstrap',
                request_serializer=m2n__bootstrap__pb2.GetM2nBootstrapRequest.SerializeToString,
                response_deserializer=m2n__bootstrap__pb2.GetM2nBootstrapResponse.FromString,
                _registered_method=True)
        self.AbortBootstrap = channel.unary_unary(
                '/model_express.m2n_bootstrap.M2nBootstrapService/AbortBootstrap',
                request_serializer=m2n__bootstrap__pb2.AbortM2nBootstrapRequest.SerializeToString,
                response_deserializer=m2n__bootstrap__pb2.AbortM2nBootstrapResponse.FromString,
                _registered_method=True)


class M2nBootstrapServiceServicer(object):
    """Ephemeral control-plane broker for a coordinator-defined NCCL communicator.
    NeMo RL/Dynamo owns membership and rank assignment; ModelExpress only stores
    an immutable UID record and fences aborted or expired attempts.
    """

    def PublishBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_M2nBootstrapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishBootstrap,
                    request_deserializer=m2n__bootstrap__pb2.PublishM2nBootstrapRequest.FromString,
                    response_serializer=m2n__bootstrap__pb2.PublishM2nBootstrapResponse.SerializeToString,
            ),
            'GetBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBootstrap,
                    request_deserializer=m2n__bootstrap__pb2.GetM2nBootstrapRequest.FromString,
                    response_serializer=m2n__bootstrap__pb2.GetM2nBootstrapResponse.SerializeToString,
            ),
            'AbortBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortBootstrap,
                    request_deserializer=m2n__bootstrap__pb2.AbortM2nBootstrapRequest.FromString,
                    response_serializer=m2n__bootstrap__pb2.AbortM2nBootstrapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.m2n_bootstrap.M2nBootstrapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.m2n_bootstrap.M2nBootstrapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class M2nBootstrapService(object):
    """Ephemeral control-plane broker for a coordinator-defined NCCL communicator.
    NeMo RL/Dynamo owns membership and rank assignment; ModelExpress only stores
    an immutable UID record and fences aborted or expired attempts.
    """

    @staticmethod
    def PublishBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.m2n_bootstrap.M2nBootstrapService/PublishBootstrap',
            m2n__bootstrap__pb2.PublishM2nBootstrapRequest.SerializeToString,
            m2n__bootstrap__pb2.PublishM2nBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.m2n_bootstrap.M2nBootstrapService/GetBootstrap',
            m2n__bootstrap__pb2.GetM2nBootstrapRequest.SerializeToString,
            m2n__bootstrap__pb2.GetM2nBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.m2n_bootstrap.M2nBootstrapService/AbortBootstrap',
            m2n__bootstrap__pb2.AbortM2nBootstrapRequest.SerializeToString,
            m2n__bootstrap__pb2.AbortM2nBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
