# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import revision_pb2 as revision__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in revision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RevisionCatalogServiceStub(object):
    """Stores immutable model-weight revisions and their externally visible state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishRevision = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/PublishRevision',
                request_serializer=revision__pb2.PublishRevisionRequest.SerializeToString,
                response_deserializer=revision__pb2.PublishRevisionResponse.FromString,
                _registered_method=True)
        self.GetRevision = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/GetRevision',
                request_serializer=revision__pb2.GetRevisionRequest.SerializeToString,
                response_deserializer=revision__pb2.GetRevisionResponse.FromString,
                _registered_method=True)
        self.ListReadyRevisions = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/ListReadyRevisions',
                request_serializer=revision__pb2.ListReadyRevisionsRequest.SerializeToString,
                response_deserializer=revision__pb2.ListReadyRevisionsResponse.FromString,
                _registered_method=True)
        self.GetRecoveryCandidates = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/GetRecoveryCandidates',
                request_serializer=revision__pb2.GetRecoveryCandidatesRequest.SerializeToString,
                response_deserializer=revision__pb2.GetRecoveryCandidatesResponse.FromString,
                _registered_method=True)
        self.UpdateReceiverState = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/UpdateReceiverState',
                request_serializer=revision__pb2.UpdateReceiverStateRequest.SerializeToString,
                response_deserializer=revision__pb2.UpdateReceiverStateResponse.FromString,
                _registered_method=True)
        self.CommitVersion = channel.unary_unary(
                '/model_express.revision.RevisionCatalogService/CommitVersion',
                request_serializer=revision__pb2.CommitVersionRequest.SerializeToString,
                response_deserializer=revision__pb2.CommitVersionResponse.FromString,
                _registered_method=True)


class RevisionCatalogServiceServicer(object):
    """Stores immutable model-weight revisions and their externally visible state.
    """

    def PublishRevision(self, request, context):
        """Atomically publishes one immutable, complete revision as READY.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevision(self, request, context):
        """Returns one exact revision by model and version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReadyRevisions(self, request, context):
        """Lists READY revisions in deterministic version order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecoveryCandidates(self, request, context):
        """Returns bounded exact-base recovery paths for one target revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReceiverState(self, request, context):
        """Records a receiver's externally visible transfer or install outcome.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitVersion(self, request, context):
        """Records orchestrator acceptance after the required receivers verify.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RevisionCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishRevision,
                    request_deserializer=revision__pb2.PublishRevisionRequest.FromString,
                    response_serializer=revision__pb2.PublishRevisionResponse.SerializeToString,
            ),
            'GetRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevision,
                    request_deserializer=revision__pb2.GetRevisionRequest.FromString,
                    response_serializer=revision__pb2.GetRevisionResponse.SerializeToString,
            ),
            'ListReadyRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReadyRevisions,
                    request_deserializer=revision__pb2.ListReadyRevisionsRequest.FromString,
                    response_serializer=revision__pb2.ListReadyRevisionsResponse.SerializeToString,
            ),
            'GetRecoveryCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecoveryCandidates,
                    request_deserializer=revision__pb2.GetRecoveryCandidatesRequest.FromString,
                    response_serializer=revision__pb2.GetRecoveryCandidatesResponse.SerializeToString,
            ),
            'UpdateReceiverState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReceiverState,
                    request_deserializer=revision__pb2.UpdateReceiverStateRequest.FromString,
                    response_serializer=revision__pb2.UpdateReceiverStateResponse.SerializeToString,
            ),
            'CommitVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitVersion,
                    request_deserializer=revision__pb2.CommitVersionRequest.FromString,
                    response_serializer=revision__pb2.CommitVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.revision.RevisionCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.revision.RevisionCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RevisionCatalogService(object):
    """Stores immutable model-weight revisions and their externally visible state.
    """

    @staticmethod
    def PublishRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/PublishRevision',
            revision__pb2.PublishRevisionRequest.SerializeToString,
            revision__pb2.PublishRevisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/GetRevision',
            revision__pb2.GetRevisionRequest.SerializeToString,
            revision__pb2.GetRevisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReadyRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/ListReadyRevisions',
            revision__pb2.ListReadyRevisionsRequest.SerializeToString,
            revision__pb2.ListReadyRevisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecoveryCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/GetRecoveryCandidates',
            revision__pb2.GetRecoveryCandidatesRequest.SerializeToString,
            revision__pb2.GetRecoveryCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReceiverState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/UpdateReceiverState',
            revision__pb2.UpdateReceiverStateRequest.SerializeToString,
            revision__pb2.UpdateReceiverStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.revision.RevisionCatalogService/CommitVersion',
            revision__pb2.CommitVersionRequest.SerializeToString,
            revision__pb2.CommitVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
