# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: revision.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'revision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erevision.proto\x12\x16model_express.revision\"i\n\x08S3Object\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x1b\n\x0eobject_version\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\tB\x11\n\x0f_object_version\"\xf3\x01\n\x10RevisionManifest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x16\n\x0etarget_version\x18\x02 \x01(\t\x12\x19\n\x0c\x62\x61se_version\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x62\x61se_digest\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x15\n\rtarget_digest\x18\x05 \x01(\t\x12\x15\n\rformat_digest\x18\x06 \x01(\t\x12\x31\n\x07payload\x18\x07 \x01(\x0b\x32 .model_express.revision.S3ObjectB\x0f\n\r_base_versionB\x0e\n\x0c_base_digest\"\x82\x01\n\x0eRevisionRecord\x12:\n\x08manifest\x18\x01 \x01(\x0b\x32(.model_express.revision.RevisionManifest\x12\x34\n\x05state\x18\x02 \x01(\x0e\x32%.model_express.revision.RevisionState\"T\n\x16PublishRevisionRequest\x12:\n\x08manifest\x18\x01 \x01(\x0b\x32(.model_express.revision.RevisionManifest\">\n\x12GetRevisionRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x16\n\x0etarget_version\x18\x02 \x01(\t\"A\n\x15\x43ommitRevisionRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x16\n\x0etarget_version\x18\x02 \x01(\t*g\n\rRevisionState\x12\x1e\n\x1aREVISION_STATE_UNSPECIFIED\x10\x00\x12\x18\n\x14REVISION_STATE_READY\x10\x01\x12\x1c\n\x18REVISION_STATE_COMMITTED\x10\x02\x32\xcf\x02\n\x16RevisionCatalogService\x12i\n\x0fPublishRevision\x12..model_express.revision.PublishRevisionRequest\x1a&.model_express.revision.RevisionRecord\x12\x61\n\x0bGetRevision\x12*.model_express.revision.GetRevisionRequest\x1a&.model_express.revision.RevisionRecord\x12g\n\x0e\x43ommitRevision\x12-.model_express.revision.CommitRevisionRequest\x1a&.model_express.revision.RevisionRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'revision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVISIONSTATE']._serialized_start=745
  _globals['_REVISIONSTATE']._serialized_end=848
  _globals['_S3OBJECT']._serialized_start=42
  _globals['_S3OBJECT']._serialized_end=147
  _globals['_REVISIONMANIFEST']._serialized_start=150
  _globals['_REVISIONMANIFEST']._serialized_end=393
  _globals['_REVISIONRECORD']._serialized_start=396
  _globals['_REVISIONRECORD']._serialized_end=526
  _globals['_PUBLISHREVISIONREQUEST']._serialized_start=528
  _globals['_PUBLISHREVISIONREQUEST']._serialized_end=612
  _globals['_GETREVISIONREQUEST']._serialized_start=614
  _globals['_GETREVISIONREQUEST']._serialized_end=676
  _globals['_COMMITREVISIONREQUEST']._serialized_start=678
  _globals['_COMMITREVISIONREQUEST']._serialized_end=743
  _globals['_REVISIONCATALOGSERVICE']._serialized_start=851
  _globals['_REVISIONCATALOGSERVICE']._serialized_end=1186
# @@protoc_insertion_point(module_scope)
