# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import weight_sync_pb2 as weight__sync__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weight_sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeightSyncServiceStub(object):
    """WeightSyncService: server-side plan building for trainer-inference weight sync.

    Protocol (PULL mode):
    1. Trainer calls PublishTrainerTable with the full shard layout.
    2. One inference worker calls BuildPlan with its resolved element-run
    regions (baked + resolved client-side, torch-dependent).
    3. Server routes regions against the TrainerTable (pure Rust arithmetic),
    builds RdmaDescriptors, caches by plan_id.
    4. All workers with the same plan_key call GetPlan to retrieve the cached
    descriptors without repeating routing work.
    5. Trainer calls InvalidatePlan when weights are resharded.

    Protocol (PUSH mode):
    1. Inference workers call PublishInferenceTable with their parameter
    GPU addresses and NIXL metadata.
    2. Trainer calls BuildPushPlan / GetPlan symmetrically.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishTrainerTable = channel.unary_unary(
                '/weight_sync.WeightSyncService/PublishTrainerTable',
                request_serializer=weight__sync__pb2.PublishTrainerTableRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.PublishTrainerTableResponse.FromString,
                _registered_method=True)
        self.GetTrainerTable = channel.unary_unary(
                '/weight_sync.WeightSyncService/GetTrainerTable',
                request_serializer=weight__sync__pb2.GetTrainerTableRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.GetTrainerTableResponse.FromString,
                _registered_method=True)
        self.PublishInferenceTable = channel.unary_unary(
                '/weight_sync.WeightSyncService/PublishInferenceTable',
                request_serializer=weight__sync__pb2.PublishInferenceTableRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.PublishInferenceTableResponse.FromString,
                _registered_method=True)
        self.BuildPlan = channel.unary_unary(
                '/weight_sync.WeightSyncService/BuildPlan',
                request_serializer=weight__sync__pb2.BuildPlanRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.BuildPlanResponse.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/weight_sync.WeightSyncService/GetPlan',
                request_serializer=weight__sync__pb2.GetPlanRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.GetPlanResponse.FromString,
                _registered_method=True)
        self.InvalidatePlan = channel.unary_unary(
                '/weight_sync.WeightSyncService/InvalidatePlan',
                request_serializer=weight__sync__pb2.InvalidatePlanRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.InvalidatePlanResponse.FromString,
                _registered_method=True)
        self.RegisterM2nWorker = channel.unary_unary(
                '/weight_sync.WeightSyncService/RegisterM2nWorker',
                request_serializer=weight__sync__pb2.RegisterM2nWorkerRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.RegisterM2nWorkerResponse.FromString,
                _registered_method=True)
        self.GetM2nPlan = channel.unary_unary(
                '/weight_sync.WeightSyncService/GetM2nPlan',
                request_serializer=weight__sync__pb2.GetM2nPlanRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.GetM2nPlanResponse.FromString,
                _registered_method=True)
        self.InvalidateM2nPlan = channel.unary_unary(
                '/weight_sync.WeightSyncService/InvalidateM2nPlan',
                request_serializer=weight__sync__pb2.InvalidateM2nPlanRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.InvalidateM2nPlanResponse.FromString,
                _registered_method=True)
        self.PublishNcclBootstrap = channel.unary_unary(
                '/weight_sync.WeightSyncService/PublishNcclBootstrap',
                request_serializer=weight__sync__pb2.PublishNcclBootstrapRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.PublishNcclBootstrapResponse.FromString,
                _registered_method=True)
        self.GetNcclBootstrap = channel.unary_unary(
                '/weight_sync.WeightSyncService/GetNcclBootstrap',
                request_serializer=weight__sync__pb2.GetNcclBootstrapRequest.SerializeToString,
                response_deserializer=weight__sync__pb2.GetNcclBootstrapResponse.FromString,
                _registered_method=True)


class WeightSyncServiceServicer(object):
    """WeightSyncService: server-side plan building for trainer-inference weight sync.

    Protocol (PULL mode):
    1. Trainer calls PublishTrainerTable with the full shard layout.
    2. One inference worker calls BuildPlan with its resolved element-run
    regions (baked + resolved client-side, torch-dependent).
    3. Server routes regions against the TrainerTable (pure Rust arithmetic),
    builds RdmaDescriptors, caches by plan_id.
    4. All workers with the same plan_key call GetPlan to retrieve the cached
    descriptors without repeating routing work.
    5. Trainer calls InvalidatePlan when weights are resharded.

    Protocol (PUSH mode):
    1. Inference workers call PublishInferenceTable with their parameter
    GPU addresses and NIXL metadata.
    2. Trainer calls BuildPushPlan / GetPlan symmetrically.
    """

    def PublishTrainerTable(self, request, context):
        """Trainer publishes its full shard layout (called once per broadcast step).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainerTable(self, request, context):
        """Retrieve the current TrainerTable for a model (called by workers at init).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishInferenceTable(self, request, context):
        """Inference worker publishes its live parameter GPU addresses (PUSH mode).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildPlan(self, request, context):
        """Submit resolved element-run regions; server routes and caches the plan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Retrieve a previously built plan by plan_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidatePlan(self, request, context):
        """Invalidate a cached plan (call when trainer reshards or worker restarts).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterM2nWorker(self, request, context):
        """Register this worker for a globally-coordinated M2N plan.
        The server holds a barrier until total_workers workers have registered,
        then routes all workers' regions in one pass and caches per-worker slices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetM2nPlan(self, request, context):
        """Retrieve this worker's slice of the global M2N plan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateM2nPlan(self, request, context):
        """Invalidate the M2N plan for a model (call when trainer reshards).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNcclBootstrap(self, request, context):
        """Source NCCL rank 0 publishes communicator bootstrap data for one attempt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNcclBootstrap(self, request, context):
        """Participants fetch communicator bootstrap data by attempt_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeightSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishTrainerTable': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTrainerTable,
                    request_deserializer=weight__sync__pb2.PublishTrainerTableRequest.FromString,
                    response_serializer=weight__sync__pb2.PublishTrainerTableResponse.SerializeToString,
            ),
            'GetTrainerTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainerTable,
                    request_deserializer=weight__sync__pb2.GetTrainerTableRequest.FromString,
                    response_serializer=weight__sync__pb2.GetTrainerTableResponse.SerializeToString,
            ),
            'PublishInferenceTable': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishInferenceTable,
                    request_deserializer=weight__sync__pb2.PublishInferenceTableRequest.FromString,
                    response_serializer=weight__sync__pb2.PublishInferenceTableResponse.SerializeToString,
            ),
            'BuildPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildPlan,
                    request_deserializer=weight__sync__pb2.BuildPlanRequest.FromString,
                    response_serializer=weight__sync__pb2.BuildPlanResponse.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=weight__sync__pb2.GetPlanRequest.FromString,
                    response_serializer=weight__sync__pb2.GetPlanResponse.SerializeToString,
            ),
            'InvalidatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidatePlan,
                    request_deserializer=weight__sync__pb2.InvalidatePlanRequest.FromString,
                    response_serializer=weight__sync__pb2.InvalidatePlanResponse.SerializeToString,
            ),
            'RegisterM2nWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterM2nWorker,
                    request_deserializer=weight__sync__pb2.RegisterM2nWorkerRequest.FromString,
                    response_serializer=weight__sync__pb2.RegisterM2nWorkerResponse.SerializeToString,
            ),
            'GetM2nPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetM2nPlan,
                    request_deserializer=weight__sync__pb2.GetM2nPlanRequest.FromString,
                    response_serializer=weight__sync__pb2.GetM2nPlanResponse.SerializeToString,
            ),
            'InvalidateM2nPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateM2nPlan,
                    request_deserializer=weight__sync__pb2.InvalidateM2nPlanRequest.FromString,
                    response_serializer=weight__sync__pb2.InvalidateM2nPlanResponse.SerializeToString,
            ),
            'PublishNcclBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNcclBootstrap,
                    request_deserializer=weight__sync__pb2.PublishNcclBootstrapRequest.FromString,
                    response_serializer=weight__sync__pb2.PublishNcclBootstrapResponse.SerializeToString,
            ),
            'GetNcclBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNcclBootstrap,
                    request_deserializer=weight__sync__pb2.GetNcclBootstrapRequest.FromString,
                    response_serializer=weight__sync__pb2.GetNcclBootstrapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weight_sync.WeightSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weight_sync.WeightSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeightSyncService(object):
    """WeightSyncService: server-side plan building for trainer-inference weight sync.

    Protocol (PULL mode):
    1. Trainer calls PublishTrainerTable with the full shard layout.
    2. One inference worker calls BuildPlan with its resolved element-run
    regions (baked + resolved client-side, torch-dependent).
    3. Server routes regions against the TrainerTable (pure Rust arithmetic),
    builds RdmaDescriptors, caches by plan_id.
    4. All workers with the same plan_key call GetPlan to retrieve the cached
    descriptors without repeating routing work.
    5. Trainer calls InvalidatePlan when weights are resharded.

    Protocol (PUSH mode):
    1. Inference workers call PublishInferenceTable with their parameter
    GPU addresses and NIXL metadata.
    2. Trainer calls BuildPushPlan / GetPlan symmetrically.
    """

    @staticmethod
    def PublishTrainerTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/PublishTrainerTable',
            weight__sync__pb2.PublishTrainerTableRequest.SerializeToString,
            weight__sync__pb2.PublishTrainerTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainerTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/GetTrainerTable',
            weight__sync__pb2.GetTrainerTableRequest.SerializeToString,
            weight__sync__pb2.GetTrainerTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishInferenceTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/PublishInferenceTable',
            weight__sync__pb2.PublishInferenceTableRequest.SerializeToString,
            weight__sync__pb2.PublishInferenceTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/BuildPlan',
            weight__sync__pb2.BuildPlanRequest.SerializeToString,
            weight__sync__pb2.BuildPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/GetPlan',
            weight__sync__pb2.GetPlanRequest.SerializeToString,
            weight__sync__pb2.GetPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/InvalidatePlan',
            weight__sync__pb2.InvalidatePlanRequest.SerializeToString,
            weight__sync__pb2.InvalidatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterM2nWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/RegisterM2nWorker',
            weight__sync__pb2.RegisterM2nWorkerRequest.SerializeToString,
            weight__sync__pb2.RegisterM2nWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetM2nPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/GetM2nPlan',
            weight__sync__pb2.GetM2nPlanRequest.SerializeToString,
            weight__sync__pb2.GetM2nPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateM2nPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/InvalidateM2nPlan',
            weight__sync__pb2.InvalidateM2nPlanRequest.SerializeToString,
            weight__sync__pb2.InvalidateM2nPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNcclBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/PublishNcclBootstrap',
            weight__sync__pb2.PublishNcclBootstrapRequest.SerializeToString,
            weight__sync__pb2.PublishNcclBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNcclBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weight_sync.WeightSyncService/GetNcclBootstrap',
            weight__sync__pb2.GetNcclBootstrapRequest.SerializeToString,
            weight__sync__pb2.GetNcclBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
