# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# cargo-deny plugin for linting dependencies
# https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
confidence-threshold = 0.93
allow = [
    "MIT-0",
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "OpenSSL",
    "Unicode-3.0",
    "BSL-1.0",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
    "Zlib"
]

# TODO exceptions
# MIT: https://github.com/guidance-ai/llguidance
#  "llguidance",
# MIT: https://github.com/guidance-ai/llguidance/toktrie
#  "toktrie",
# MIT: https://github.com/guidance-ai/llguidance/toktrie_hf_tokenizers
#  "toktrie_hf_tokenizers",

[[licenses.clarify]]

name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
deny = [
	# Ensure we don't depend on openssl
    { name = "native-tls" },
    { name = "openssl-sys" },
]
