apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-express-server
  labels:
    app: model-express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-express-server
  template:
    metadata:
      labels:
        app: model-express-server
    spec:
      containers:
      - name: model-express-server
        image: model-express-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SERVER_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "info"
        - name: HF_HUB_CACHE
          value: "/cache/models"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: model-cache
          mountPath: /cache
        - name: model-db
          mountPath: /app/models.db
          subPath: models.db
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache-pvc
      - name: model-db
        persistentVolumeClaim:
          claimName: model-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: model-express-server
spec:
  selector:
    app: model-express-server
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
