# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelexpress.fullname" . }}
  labels:
    {{- include "modelexpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8001 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "modelexpress.selectorLabels" . | nindent 4 }}
