[package]
name = "model_express_client"
version = "0.1.0"
edition = "2021"

[dependencies]
model_express_common = { path = "../model_express_common" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
futures = "0.3"
uuid = { version = "1.16", features = ["v4", "serde"] }
thiserror = "2.0"

[dev-dependencies]
tokio-test = "0.4"
tonic-build = { workspace = true }
