# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import refit_collective_pb2 as refit__collective__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in refit_collective_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefitCollectiveServiceStub(object):
    """Rendezvous and admission for the NCCL M2N collective refit path.

    This service is deliberately separate from `RefitService`: that one is the
    directory for the NIXL pull path, where a generator discovers shards and
    reads them one-sidedly. Here both sides enter one collective together, so MX
    brokers the NCCL bootstrap instead of a shard table, and owns admission,
    rank assignment, worker-generation fencing, and a readiness state the
    trainer can observe before it launches.

    Weight bytes never reach this service. Neither does the reshard plan: MX
    stores only its digest and the endpoint that serves it, as the pull path
    does for tensor manifests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollectiveTransfer = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/CreateCollectiveTransfer',
                request_serializer=refit__collective__pb2.CreateCollectiveTransferRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveTransfer.FromString,
                _registered_method=True)
        self.GetCollectiveTransfer = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/GetCollectiveTransfer',
                request_serializer=refit__collective__pb2.GetCollectiveTransferRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveTransfer.FromString,
                _registered_method=True)
        self.DeleteCollectiveTransfer = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/DeleteCollectiveTransfer',
                request_serializer=refit__collective__pb2.DeleteCollectiveTransferRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveTransfer.FromString,
                _registered_method=True)
        self.JoinCollectiveGroup = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/JoinCollectiveGroup',
                request_serializer=refit__collective__pb2.JoinCollectiveGroupRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveGroupMembership.FromString,
                _registered_method=True)
        self.GetCollectiveGroup = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/GetCollectiveGroup',
                request_serializer=refit__collective__pb2.GetCollectiveGroupRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveGroup.FromString,
                _registered_method=True)
        self.PublishGroupBootstrap = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/PublishGroupBootstrap',
                request_serializer=refit__collective__pb2.PublishGroupBootstrapRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveGroup.FromString,
                _registered_method=True)
        self.ReportCollectiveTransfer = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveService/ReportCollectiveTransfer',
                request_serializer=refit__collective__pb2.ReportCollectiveTransferRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.CollectiveTransfer.FromString,
                _registered_method=True)


class RefitCollectiveServiceServicer(object):
    """Rendezvous and admission for the NCCL M2N collective refit path.

    This service is deliberately separate from `RefitService`: that one is the
    directory for the NIXL pull path, where a generator discovers shards and
    reads them one-sidedly. Here both sides enter one collective together, so MX
    brokers the NCCL bootstrap instead of a shard table, and owns admission,
    rank assignment, worker-generation fencing, and a readiness state the
    trainer can observe before it launches.

    Weight bytes never reach this service. Neither does the reshard plan: MX
    stores only its digest and the endpoint that serves it, as the pull path
    does for tensor manifests.
    """

    def CreateCollectiveTransfer(self, request, context):
        """Orchestrator-facing. `idempotency_key` makes a retried create return the
        same operation rather than opening a second one against the same group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectiveTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollectiveTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinCollectiveGroup(self, request, context):
        """Worker-client-facing. Workers join a group; they never create or delete
        one. Groups are reclaimed automatically once every participant's
        `WorkerRegistration` has lapsed and no transfer still references them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectiveGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishGroupBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCollectiveTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefitCollectiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollectiveTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollectiveTransfer,
                    request_deserializer=refit__collective__pb2.CreateCollectiveTransferRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveTransfer.SerializeToString,
            ),
            'GetCollectiveTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectiveTransfer,
                    request_deserializer=refit__collective__pb2.GetCollectiveTransferRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveTransfer.SerializeToString,
            ),
            'DeleteCollectiveTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollectiveTransfer,
                    request_deserializer=refit__collective__pb2.DeleteCollectiveTransferRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveTransfer.SerializeToString,
            ),
            'JoinCollectiveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinCollectiveGroup,
                    request_deserializer=refit__collective__pb2.JoinCollectiveGroupRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveGroupMembership.SerializeToString,
            ),
            'GetCollectiveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectiveGroup,
                    request_deserializer=refit__collective__pb2.GetCollectiveGroupRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveGroup.SerializeToString,
            ),
            'PublishGroupBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishGroupBootstrap,
                    request_deserializer=refit__collective__pb2.PublishGroupBootstrapRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveGroup.SerializeToString,
            ),
            'ReportCollectiveTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCollectiveTransfer,
                    request_deserializer=refit__collective__pb2.ReportCollectiveTransferRequest.FromString,
                    response_serializer=refit__collective__pb2.CollectiveTransfer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.refit_collective.RefitCollectiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.refit_collective.RefitCollectiveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefitCollectiveService(object):
    """Rendezvous and admission for the NCCL M2N collective refit path.

    This service is deliberately separate from `RefitService`: that one is the
    directory for the NIXL pull path, where a generator discovers shards and
    reads them one-sidedly. Here both sides enter one collective together, so MX
    brokers the NCCL bootstrap instead of a shard table, and owns admission,
    rank assignment, worker-generation fencing, and a readiness state the
    trainer can observe before it launches.

    Weight bytes never reach this service. Neither does the reshard plan: MX
    stores only its digest and the endpoint that serves it, as the pull path
    does for tensor manifests.
    """

    @staticmethod
    def CreateCollectiveTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/CreateCollectiveTransfer',
            refit__collective__pb2.CreateCollectiveTransferRequest.SerializeToString,
            refit__collective__pb2.CollectiveTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectiveTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/GetCollectiveTransfer',
            refit__collective__pb2.GetCollectiveTransferRequest.SerializeToString,
            refit__collective__pb2.CollectiveTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollectiveTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/DeleteCollectiveTransfer',
            refit__collective__pb2.DeleteCollectiveTransferRequest.SerializeToString,
            refit__collective__pb2.CollectiveTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinCollectiveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/JoinCollectiveGroup',
            refit__collective__pb2.JoinCollectiveGroupRequest.SerializeToString,
            refit__collective__pb2.CollectiveGroupMembership.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectiveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/GetCollectiveGroup',
            refit__collective__pb2.GetCollectiveGroupRequest.SerializeToString,
            refit__collective__pb2.CollectiveGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishGroupBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/PublishGroupBootstrap',
            refit__collective__pb2.PublishGroupBootstrapRequest.SerializeToString,
            refit__collective__pb2.CollectiveGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCollectiveTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveService/ReportCollectiveTransfer',
            refit__collective__pb2.ReportCollectiveTransferRequest.SerializeToString,
            refit__collective__pb2.CollectiveTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RefitCollectiveWorkerServiceStub(object):
    """Worker-to-worker. The trainer that MX ranks first in the group serves the
    reshard plan; every other participant fetches it and verifies the digest MX
    advertised before issuing any wire operation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReshardPlan = channel.unary_unary(
                '/model_express.refit_collective.RefitCollectiveWorkerService/GetReshardPlan',
                request_serializer=refit__collective__pb2.GetReshardPlanRequest.SerializeToString,
                response_deserializer=refit__collective__pb2.GetReshardPlanResponse.FromString,
                _registered_method=True)


class RefitCollectiveWorkerServiceServicer(object):
    """Worker-to-worker. The trainer that MX ranks first in the group serves the
    reshard plan; every other participant fetches it and verifies the digest MX
    advertised before issuing any wire operation.
    """

    def GetReshardPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefitCollectiveWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReshardPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReshardPlan,
                    request_deserializer=refit__collective__pb2.GetReshardPlanRequest.FromString,
                    response_serializer=refit__collective__pb2.GetReshardPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.refit_collective.RefitCollectiveWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.refit_collective.RefitCollectiveWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefitCollectiveWorkerService(object):
    """Worker-to-worker. The trainer that MX ranks first in the group serves the
    reshard plan; every other participant fetches it and verifies the digest MX
    advertised before issuing any wire operation.
    """

    @staticmethod
    def GetReshardPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit_collective.RefitCollectiveWorkerService/GetReshardPlan',
            refit__collective__pb2.GetReshardPlanRequest.SerializeToString,
            refit__collective__pb2.GetReshardPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
