# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""K8s integration test for row 18 — Stale Metadata After Source Death.

Sequence:
  1. Connect to mx-server:8001 via kubectl port-forward.
  2. Call ListSources(status_filter=READY); expect exactly 1 instance
     (the live source).
  3. Force-delete the source pod with --grace-period=0.
  4. Sleep MX_HEARTBEAT_TIMEOUT_SECS + MX_REAPER_SCAN_INTERVAL_SECS + buffer.
     With the compressed reaper knobs in mx-server-redis.yaml that's 30 + 10
     + 20 = 60s.
  5. Call ListSources(status_filter=READY) again; expect 0 instances. The
     server's reaper should have transitioned the dead source from READY to
     STALE, and the status_filter=READY query excludes STALE entries.

Backend-agnostic — the reaper logic is identical for Redis and K8s CRD
backends. This test runs against the Redis backend by virtue of how the
composite action wires the mx-server manifest, but the same assertions
would hold against K8s CRD if/when we matrix that in.

The proto stubs (p2p_pb2.py, p2p_pb2_grpc.py) are generated into the test
directory by the composite action's grpc_tools.protoc step before pytest
runs. We import them as top-level modules to avoid pulling in the full
modelexpress python package (which has torch / nixl deps that are heavy
to install just for two gRPC stubs).
"""

import socket
import subprocess
import sys
import time
from contextlib import contextmanager

import grpc

# Stubs are generated by the action into the same directory as this test file.
sys.path.insert(0, "ci/k8s/client")
import p2p_pb2  # noqa: E402
import p2p_pb2_grpc  # noqa: E402


# Safety margin on top of (heartbeat_timeout + reaper_scan_interval) so that
# even if the kill lands just after a reaper scan tick, we still observe the
# READY→STALE transition before checking. Sized at one extra scan interval's
# worth of slack — this is a test-only constant; reaper timing comes from the
# action via fixtures so the server config and the test stay aligned.
STALE_DETECTION_BUFFER_SECS = 20

MX_SERVER_LOCAL_PORT = 18001
MX_SERVER_REMOTE_PORT = 8000

SOURCE_JOB_LABEL = "job-name=mx-source"


@contextmanager
def _port_forward(namespace: str, target: str, local_port: int, remote_port: int):
    """Port-forward to an in-cluster Service. Yields once a raw TCP connection
    succeeds (or the deadline elapses, in which case the gRPC call inside the
    with-block surfaces the real failure)."""
 
    proc = subprocess.Popen(
        ["kubectl", "-n", namespace, "port-forward", target, f"{local_port}:{remote_port}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        deadline = time.perf_counter() + 60
        while time.perf_counter() < deadline:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.settimeout(2)
                try:
                    sock.connect(("localhost", local_port))
                    break
                except (ConnectionRefusedError, socket.timeout, OSError):
                    time.sleep(1)
        yield local_port
    finally:
        proc.terminate()
        proc.wait(timeout=5)


def _list_ready_sources(stub: "p2p_pb2_grpc.P2pServiceStub") -> list:
    """Return every READY source the server knows about.

    No identity filter on purpose: the server's `list_sources` computes
    `mx_source_id` as a SHA256 over all 11 identity fields (model_name,
    tp/pp/ep size, dtype, revision, mx_version, …) and compares against
    that hash. A partial identity from outside the engine doesn't produce
    a matching hash, so the only honest "all sources for this test" query
    is one with no identity set — relying on status_filter and the test
    namespace's single-tenant invariant (one source pod per run).
    """
    request = p2p_pb2.ListSourcesRequest(
        status_filter=p2p_pb2.SOURCE_STATUS_READY,
    )
    response = stub.ListSources(request, timeout=30)
    return list(response.instances)


def test_stale_metadata_excluded_after_heartbeat_timeout(
    namespace: str,
    heartbeat_timeout_secs: int,
    reaper_scan_interval_secs: int,
) -> None:
    """End-to-end staleness check.

    Run order (gated by `--tb=short` so the assertion message is the
    primary signal):
      - Before kill: server returns exactly 1 READY source.
      - After kill + wait_secs: server returns 0 READY sources.

    `wait_secs` is computed from the fixture values that the composite
    action threads in from the same inputs it gave the deployed server,
    so the test's wait window always tracks the actual server config.

    If the second assertion fires with > 0 instances, the reaper isn't
    transitioning the dead source to STALE in time — could be a bug in
    the reaper, in the heartbeat path, or in the status_filter handling.
    """
    wait_secs = heartbeat_timeout_secs + reaper_scan_interval_secs + STALE_DETECTION_BUFFER_SECS
    with _port_forward(namespace, "svc/mx-server", MX_SERVER_LOCAL_PORT, MX_SERVER_REMOTE_PORT) as port:
        channel = grpc.insecure_channel(f"localhost:{port}")
        stub = p2p_pb2_grpc.P2pServiceStub(channel)

        live = _list_ready_sources(stub)
        print(f"[before-kill] {len(live)} READY source(s): {[s.worker_id for s in live]}")
        assert len(live) == 1, (
            f"Expected exactly 1 READY source before kill, got {len(live)}. "
            f"This means the source either never published or there are leftover "
            f"sources from a previous test run."
        )

        # Force-delete the source pod. --grace-period=0 + --force simulates
        # sudden death (no graceful shutdown signal to the modelexpress
        # client, so it can't deregister itself with the server — exactly
        # the failure mode the reaper is supposed to handle).
        result = subprocess.run(
            ["kubectl", "-n", namespace, "delete", "pod", "-l", SOURCE_JOB_LABEL,
             "--grace-period=0", "--force"],
            capture_output=True, text=True, check=True,
        )
        print(f"[kill] {result.stdout.strip()}")

        # Wait for the heartbeat-timeout + one reaper scan + a buffer scan.
        # The reaper polls on a fixed interval, so a missed deadline can
        # take up to one full scan to surface.
        print(
            f"[wait] sleeping {wait_secs}s for the reaper to mark the dead source STALE "
            f"(heartbeat={heartbeat_timeout_secs}s + scan={reaper_scan_interval_secs}s + buffer={STALE_DETECTION_BUFFER_SECS}s)..."
        )
        time.sleep(wait_secs)

        stale = _list_ready_sources(stub)
        print(f"[after-wait] {len(stale)} READY source(s): {[s.worker_id for s in stale]}")
        assert len(stale) == 0, (
            f"Expected 0 READY sources after {wait_secs}s with no live source, "
            f"got {len(stale)}: {[s.worker_id for s in stale]}. "
            f"The reaper failed to transition the dead source from READY → STALE "
            f"within the configured heartbeat window."
        )
