#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Merge per-source compliance outputs into a single NOTICES and OSRB CSV.

The per-source generators run in different build environments (Rust in the
server image, dpkg in the runtime image, pypi once per target architecture).
This script unions their outputs into the two artifacts submitted to OSRB:

    NOTICES   - Rust + Python license texts, deduped across architectures.
    osrb.csv  - All rows (rust + dpkg + pypi), deduped on type+name+version.

Example (after downloading CI artifacts):
    python3 consolidate_compliance.py \
        --md ATTRIBUTIONS_Rust.md \
        --md NOTICES_Python_amd64.md --md NOTICES_Python_arm64.md \
        --csv rust_deps.csv \
        --csv dpkg_amd64.csv --csv dpkg_arm64.csv \
        --csv pypi_amd64.csv --csv pypi_arm64.csv \
        --out-notices NOTICES --out-csv osrb.csv

dpkg packages contribute CSV rows only; their license texts live at the
well-known /usr/share/doc/<pkg>/copyright path inside the image, so they are
intentionally absent from NOTICES.
"""

import argparse
import csv

OSRB_HEADER = ["type", "name", "version", "spdx_license"]

NOTICES_HEADER = """\
<!--
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
-->

# Third-Party Software Attributions

This file lists the third-party software bundled in or required at runtime by
the ModelExpress server binaries (Rust) and the Python client wheel (Python),
across all supported architectures. Each component is licensed under the terms
shown below.

This file is automatically generated. Please do not edit it directly.
"""


def merge_csv(paths, out_path):
    seen = set()
    rows = []
    for path in paths:
        with open(path, newline="") as f:
            reader = csv.reader(f)
            header = next(reader, None)
            if header and [h.strip().lower() for h in header] != OSRB_HEADER:
                # Tolerate a legacy `license` header from older outputs.
                if [h.strip().lower() for h in header][:3] != OSRB_HEADER[:3]:
                    raise ValueError(f"{path}: unexpected header {header}")
            for row in reader:
                if len(row) < 4:
                    continue
                key = (row[0], row[1], row[2])
                if key in seen:
                    continue
                seen.add(key)
                rows.append(row[:4])

    rows.sort(key=lambda r: (r[0], r[1].lower(), r[2]))
    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(OSRB_HEADER)
        writer.writerows(rows)
    return len(rows)


def extract_blocks(path):
    """Yield (header_line, block_text) for each `## ...` component section.

    Fence-aware: a `## ` line inside a ``` code fence is part of a license body
    (e.g. a license whose clauses are numbered `## 1.`), not a new component.
    """
    with open(path) as f:
        lines = f.read().split("\n")

    in_fence = False
    header = None
    body = []
    for line in lines:
        if line.startswith("```"):
            in_fence = not in_fence
        if not in_fence and line.startswith("## "):
            if header is not None:
                yield header, "\n".join([header] + body).rstrip()
            header = line.strip()
            body = []
        elif header is not None:
            body.append(line)
    if header is not None:
        yield header, "\n".join([header] + body).rstrip()


def merge_notices(paths, out_path):
    seen = set()
    blocks = []
    # Insertion order is preserved: inputs are pre-sorted within themselves, so
    # the result is Rust crates first, then Python packages not already listed.
    for path in paths:
        for header, block in extract_blocks(path):
            if header in seen:
                continue
            seen.add(header)
            blocks.append(block)

    with open(out_path, "w") as f:
        f.write(NOTICES_HEADER)
        f.write("\n")
        f.write("\n\n".join(blocks))
        f.write("\n")
    return len(blocks)


def main():
    parser = argparse.ArgumentParser(
        description="Merge per-source compliance outputs into NOTICES and an OSRB CSV."
    )
    parser.add_argument("--md", action="append", default=[], help="Input NOTICES markdown (repeatable).")
    parser.add_argument("--csv", action="append", default=[], help="Input OSRB CSV (repeatable).")
    parser.add_argument("--out-notices", default="NOTICES", help="Merged NOTICES output path.")
    parser.add_argument("--out-csv", default="osrb.csv", help="Merged OSRB CSV output path.")
    args = parser.parse_args()

    if args.csv:
        n = merge_csv(args.csv, args.out_csv)
        print(f"{args.out_csv}: {n} unique rows from {len(args.csv)} file(s)")
    if args.md:
        n = merge_notices(args.md, args.out_notices)
        print(f"{args.out_notices}: {n} unique component blocks from {len(args.md)} file(s)")


if __name__ == "__main__":
    main()
