#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ATTRIBUTIONS_Rust.md and ATTRIBUTIONS_Rust.csv from cargo-about JSON.

Usage:
    cargo about generate --format json -o licenses.json
    python3 generate_attributions.py licenses.json

Or via stdin:
    cargo about generate --format json | python3 generate_attributions.py

Outputs:
    ATTRIBUTIONS_Rust.md  - Full license texts for container inclusion
    ATTRIBUTIONS_Rust.csv - Summary with type, name, version, SPDX license

Requires cargo-about (https://github.com/EmbarkStudios/cargo-about).
Configure accepted licenses in about.toml before running.
"""

import csv
import json
import os
import re
import sys


def make_license_label(source_path, repo_url):
    """Convert a local license file path to a GitHub raw URL or a short label."""
    if not source_path:
        return "LICENSE"

    # Extract just the filename from the local path
    filename = os.path.basename(source_path)

    # If we have a GitHub repo URL, construct a raw content URL
    if repo_url:
        gh_match = re.match(r"https://github\.com/([^/]+/[^/]+)", repo_url)
        if gh_match:
            gh_repo = gh_match.group(1)
            return f"https://raw.githubusercontent.com/{gh_repo}/HEAD/{filename}"

    return filename


HEADER = """\
<!--
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

# Third-Party Software Attributions

This project uses the following third-party libraries. Each library is open-source and licensed under the terms indicated below.

This file is automatically generated. Please do not edit it directly.
"""


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    crates = data["crates"]
    licenses = data["licenses"]

    # Build mapping: crate_id -> list of (license_id, source_path, text)
    crate_licenses = {}
    for lic in licenses:
        for used in lic["used_by"]:
            crate_info = used["crate"]
            crate_id = crate_info["id"]
            if crate_id not in crate_licenses:
                crate_licenses[crate_id] = []
            crate_licenses[crate_id].append(
                {
                    "id": lic["id"],
                    "source_path": lic["source_path"],
                    "text": lic["text"],
                }
            )

    # Filter out workspace (first-party) crates
    crates = [
        c
        for c in crates
        if c["package"].get("source") is not None
    ]

    # Sort crates alphabetically by name, then version
    sorted_crates = sorted(
        crates,
        key=lambda c: (c["package"]["name"].lower(), c["package"]["version"]),
    )

    output = [HEADER]

    for crate in sorted_crates:
        pkg = crate["package"]
        name = pkg["name"]
        version = pkg["version"]
        repo = pkg.get("repository") or pkg.get("homepage") or ""
        license_expr = crate["license"]
        crate_id = pkg["id"]

        output.append(f"## {name} - {version}")
        if repo:
            output.append(f"**Repository URL**: {repo}")
        output.append(f"**License Type(s)**: {license_expr}")

        # Get license texts for this crate
        lic_entries = crate_licenses.get(crate_id, [])
        for lic in lic_entries:
            label = make_license_label(lic["source_path"], repo)
            # Normalize line endings and strip trailing whitespace
            text = lic["text"].replace("\r\n", "\n").replace("\r", "\n").rstrip()
            output.append(f"### License: {label}")
            output.append(f"```\n{text}\n```")
            output.append("")

        output.append("")

    with open("ATTRIBUTIONS_Rust.md", "w") as f:
        f.write("\n".join(output).rstrip())
        f.write("\n")

    with open("ATTRIBUTIONS_Rust.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["type", "name", "version", "license"])
        for crate in sorted_crates:
            pkg = crate["package"]
            writer.writerow(["rust", pkg["name"], pkg["version"], crate["license"]])


if __name__ == "__main__":
    main()
