#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the Rust section of NOTICES and the rust OSRB CSV from cargo-about.

Usage:
    cargo about generate --format json -o licenses.json
    python3 generate_attributions.py licenses.json

Or via stdin:
    cargo about generate --format json | python3 generate_attributions.py

Outputs (paths configurable via flags):
    NOTICES_Rust.md  - Full license texts for the Rust runtime dependencies.
    rust_deps.csv    - OSRB rows: type,name,version,spdx_license (type=rust).

Only runtime crates are included: about.toml sets ignore-build-dependencies
and ignore-dev-dependencies, and first-party workspace crates (those with no
`source`) are filtered out here.

Requires cargo-about (https://github.com/EmbarkStudios/cargo-about).
Configure accepted licenses in about.toml before running.
"""

import argparse
import csv
import json
import os
import re
import sys

# OSRB CSV header shared across all generators (rust / dpkg / pypi).
OSRB_HEADER = ["type", "name", "version", "spdx_license"]


def make_license_label(source_path, repo_url):
    """Convert a local license file path to a GitHub raw URL or a short label."""
    if not source_path:
        return "LICENSE"

    filename = os.path.basename(source_path)

    if repo_url:
        gh_match = re.match(r"https://github\.com/([^/]+/[^/]+)", repo_url)
        if gh_match:
            gh_repo = gh_match.group(1)
            return f"https://raw.githubusercontent.com/{gh_repo}/HEAD/{filename}"

    return filename


HEADER = """\
<!--
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

# Third-Party Software Attributions (Rust)

This file lists the Rust runtime dependencies of the ModelExpress server
binaries. Each library is open-source and licensed under the terms indicated
below.

This file is automatically generated. Please do not edit it directly.
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate Rust NOTICES section and OSRB CSV from cargo-about JSON."
    )
    parser.add_argument(
        "licenses_json",
        nargs="?",
        help="Path to cargo-about JSON output. Reads stdin if omitted.",
    )
    parser.add_argument(
        "--md-output", default="NOTICES_Rust.md", help="Markdown output path."
    )
    parser.add_argument(
        "--csv-output", default="rust_deps.csv", help="OSRB CSV output path."
    )
    args = parser.parse_args()

    if args.licenses_json:
        with open(args.licenses_json) as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    crates = data["crates"]
    licenses = data["licenses"]

    # Build mapping: crate_id -> list of (license_id, source_path, text)
    crate_licenses = {}
    for lic in licenses:
        for used in lic["used_by"]:
            crate_info = used["crate"]
            crate_id = crate_info["id"]
            crate_licenses.setdefault(crate_id, []).append(
                {
                    "id": lic["id"],
                    "source_path": lic["source_path"],
                    "text": lic["text"],
                }
            )

    # Filter out workspace (first-party) crates: they have no upstream source.
    crates = [c for c in crates if c["package"].get("source") is not None]

    sorted_crates = sorted(
        crates,
        key=lambda c: (c["package"]["name"].lower(), c["package"]["version"]),
    )

    output = [HEADER]

    for crate in sorted_crates:
        pkg = crate["package"]
        name = pkg["name"]
        version = pkg["version"]
        repo = pkg.get("repository") or pkg.get("homepage") or ""
        license_expr = crate["license"]
        crate_id = pkg["id"]

        output.append(f"## {name} - {version}")
        if repo:
            output.append(f"**Repository URL**: {repo}")
        output.append(f"**License Type(s)**: {license_expr}")

        for lic in crate_licenses.get(crate_id, []):
            label = make_license_label(lic["source_path"], repo)
            text = lic["text"].replace("\r\n", "\n").replace("\r", "\n").rstrip()
            output.append(f"### License: {label}")
            output.append(f"```\n{text}\n```")
            output.append("")

        output.append("")

    with open(args.md_output, "w") as f:
        f.write("\n".join(output).rstrip())
        f.write("\n")

    with open(args.csv_output, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(OSRB_HEADER)
        for crate in sorted_crates:
            pkg = crate["package"]
            writer.writerow(["rust", pkg["name"], pkg["version"], crate["license"]])


if __name__ == "__main__":
    main()
