name: Trigger CI for modelexpress

on:
  push:
    branches:
      - main
      - 'release/*.*.*'
  pull_request:
    branches:
      - main
      - 'release/*.*.*'

jobs:
  trigger:
    uses: ai-dynamo/.github/.github/workflows/mirror_and_trigger_ci.yml@pvijayakrish/add-centralized-workflows
    with:
      ref: ${{ github.ref_name }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
      MIRROR_URL: ${{ secrets.MIRROR_URL }}
      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
      PIPELINE_URL: ${{ secrets.PIPELINE_URL }}
